[app]
url = "amqp://localhost:5672"
port = 3000
ws = "wss://eth-mainnet.g.alchemy.com/v2/v6q3Yj01H1iH4T2ctJ5Nf76cnlOvOstM"

[[contracts]]
name = "usdt"
address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
events = ["Transfer", "Approval"]